package databases;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class GUITable extends javax.swing.JFrame {

    public GUITable() {
        initComponents();

        //Hides fields for adding new customer
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        AddCustomerButton.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddCustomerButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        ViewButton = new javax.swing.JButton();
        TableSelectComboBox = new javax.swing.JComboBox<>();
        DeleteButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        AddCustomerButton.setText("Add New Customer");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        ViewButton.setText("View Data");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        TableSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customers", "Products", "Order2ProductLink", "Orders" }));
        TableSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableSelectComboBoxActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete Selected");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddCustomerButton)))
                        .addGap(26, 26, 26)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(TableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewButton)
                    .addComponent(TableSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCustomerButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/OrdersDatabase", "julie", "password");//Connects to my OrdersDatabase

            //Change results set to be scrollable (otherwise you cant get individual elements)
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            //Generate primary key
            String SQL = "Select MAX(CustomerID) as maxID from TBL_Customers";
            ResultSet rs = stmt.executeQuery(SQL);

            //get value for max value in primary key column, add one to it. To be used for new primary key.
            rs.next();
            int id = rs.getInt("maxID") + 1;

            //insert a record
            SQL = "insert into TBL_Customers Values (" + id + ", '" + jTextField1.getText() + "', '" + jTextField2.getText() + "')";
            stmt.executeUpdate(SQL);

            SQL = "SELECT * FROM TBL_Customers";
            rs = stmt.executeQuery(SQL);

            UpdateTableWithResultSet(rs);
            rs.close();
            con.close();
            stmt.close();

        } catch (Exception e) {

        }


    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/OrdersDatabase", "julie", "password");//************************** Start here

            //Change results set to be scrollable (otherwise you cant get last element)
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            //Before you do this step, make a new combo box and customise code to type in table names
            //gets all records for selected table
            String SQL = "SELECT * FROM TBL_" + TableSelectComboBox.getSelectedItem();
            ResultSet rs = stmt.executeQuery(SQL);

            UpdateTableWithResultSet(rs);//Sends result set to UpdateTableWithResultSet() method

            //Housekeeping
            rs.close();
            con.close();
            stmt.close();

        } catch (SQLException e) {
            System.out.println(e);
        }

        if (TableSelectComboBox.getSelectedItem().equals("Customers")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            AddCustomerButton.setVisible(true);
            DeleteButton.setVisible(true);
        } else {
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            AddCustomerButton.setVisible(false);
            DeleteButton.setVisible(true);
        }

    }//GEN-LAST:event_ViewButtonActionPerformed

    private void TableSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableSelectComboBoxActionPerformed

    }//GEN-LAST:event_TableSelectComboBoxActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed

        try {
            //find userid for that row
            int SelectedID = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
           
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/OrdersDatabase", "julie", "password");//Connects to my OrdersDatabase
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            //Delete from table where customerId == that ID
            String SQL = "DELETE FROM TBL_CUSTOMERS WHERE CUSTOMERID = " + SelectedID;
            stmt.executeUpdate(SQL);

            //Refresh Customers table on screen
            SQL = "SELECT * FROM TBL_CUSTOMERS";
            ResultSet rs = stmt.executeQuery(SQL);

            UpdateTableWithResultSet(rs);
            rs.close();
            con.close();
            stmt.close();
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_DeleteButtonActionPerformed

    public void UpdateTableWithResultSet(ResultSet rs) {
        try {

            String[] columns = new String[rs.getMetaData().getColumnCount()];//Gets how many columns are in the table

            //Loops through metadata for selected table and adds column names to the columns array
            for (int i = 0; i < columns.length; i++) {//Loops through metadata for selected table and adds column names to the columns array
                columns[i] = rs.getMetaData().getColumnLabel(i + 1);
            }

            rs.last(); //Moves cursor to last element in result set, so we can get the number of rows in database
            int totalrows = rs.getRow();

            rs.first(); //moves cursor back to first row in database

            Object[][] rows = new Object[totalrows][columns.length];//2D object array used for tableModel

            for (int i = 0; i < totalrows; i++) { //Loops through all of the rows in the database
                for (int j = 0; j < columns.length; j++) {//For each of the rows it loops through each of the the columns     
                    rows[i][j] = rs.getObject(columns[j]); //gets the row name from the col array, gets the data in that column, and adds it to the rows 2d Array
                }
                rs.next();
            }

            //This sets up our new tableModel (This is copied by right clicking on Jtable and clicking customise code)
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    rows,
                    columns
            ));

            //jTable1.setEnabled(false); //This makes the table so you can't click on it
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JComboBox<String> TableSelectComboBox;
    private javax.swing.JButton ViewButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
